name: thesis
channels:
 - conda-forge
dependencies:
- python=3.10
- numpy
- matplotlib
- pathlib
- rasterio
- xarray 
- rioxarray
- ipykernel
- scipy
- netCDF4
- h5netcdf
- cartopy 
- geoviews
- hvplot
- jupyterlab
- fiona 
- geopandas
- dask
- seaborn
- pip
- pip:
  - pywaterinfo