name: thesis
channels:
 - conda-forge
dependencies:
- python=3.10 
- numpy
- matplotlib
- pathlib
- rasterio
- xarray=2022.11.0
- rioxarray
- ipykernel
- scipy
- netCDF4
- cartopy 
- geoviews
- hvplot
- jupyterlab
- fiona 
- geopandas=0.11
- dask
- seaborn
- python-dateutil
- pip
- pip:
  - pywaterinfo
  - openeo